import { ApolloClient, InMemoryCache } from '@apollo/client'
import Head from 'next/head'
import { GET_ALL_POSTS } from '../graphql/queries'
import Link from 'next/link';
import { IPost } from '../types';

export default function Home({posts} : { posts: IPost[]}) {
  
  return (
    <div>
      <Head>
        <title>My Blog</title>
        <meta name='description' content='Generated by create next app' />
        <link rel="icon" href="/favicon.ico" type="image/x-icon" />
      </Head>
      <h1>Welcome to the CoderBlog</h1>
      <p>lorem ipsum</p>
      <br/>
      <h2>All posts</h2>
      <br/>
      {posts.map( (post: IPost, idx: number) => {
        return (
          <Link key={idx} href={post.attributes.urlSlug}>
            <div  className="card"> 
              <h3>{post.attributes.title}</h3>
              <p>{post.attributes.description}</p>
            </div>
          </Link>
        )
      })}
    </div>
  )
}

export async function getStaticProps() {

  const client = new ApolloClient({
    uri: 'https://alberto-strapi-blog.herokuapp.com/graphql',
    cache: new InMemoryCache()
  });

  const { data } = await client.query({query: GET_ALL_POSTS});

  return {
    props: {
       posts: data.blogPosts.data
    }
  }
}  